# This contains params to be used by the stages to train or predict
model_param:
  image_shape: [180,180,3]
  Batch_size: 32
  validation_split: 0.2
  split_seed: 42
  loss: "sparse_categorical_crossentropy"
  lr : 0.001
  metrics : ["accuracy"]